### ISSUE TITLE
xpshell tests

### ISSUE THREAD

**Issue by clarkbw** [jlongster/debugger.html#19]

**Comment by jlongster** [comment]
This was done in https://github.com/jlongster/debugger.html/commit/2c6301861b4af22002b6953e765a5dce637ff3ee. This task was not about actually writing tests but setting up the environment so that we can actually run them. This is done. I've successfully run a test that imports our files.

The next step is to figure out how to write tests, see #42. Most likely we will write a small protocol stub that returns dummy data, and unit tests all the actions and various workflows. That will get us really far. Eventually we will also want to write mochitests, but we can do that later.
