### ISSUE TITLE
Fix Debugger Double Scrollbar

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#244]
I believe the tweaks to the header caused a second scrollbar to come in.

@helenvholmes have you seen this?

![screen shot 2016-06-07 at 9 36 19 am](https://cloud.githubusercontent.com/assets/254562/15859373/ea905d6c-2c92-11e6-949c-976dcdf4ade0.png)

**Comment by helenvholmes** [comment]
I've seen the second scrollbar, yes—unsure why the changes in the header are causing the second scrollbar, though 🤔

**Comment by jlongster** [comment]
It happens because the editor's height is calculated unfortunately by hardcoding the height of the header, so if you change the height of the header but not the `calc` used in the editor the editor is too tall.

@jasonLaster you're using a pretty outdated version though, I made a bunch of tiny fixes yesterday. Can you merge from master and try again?

**Comment by jasonLaster** [comment]
I don't see it anymore :)
