### ISSUE TITLE
Node version 6 is required

### ISSUE THREAD

**Issue by amitzur** [jlongster/debugger.html#284]
as of PR #280 destructuring is required. I was with node v4 so had to either run with --harmony_destructuring flag or upgrade to v6.2.2
Of course I did the latter, but maybe the readme should have a prerequisite section? I preferred bringing it up in an issue rather than a pull request

**Comment by jlongster** [comment]
Oh, thanks for pointing this out. I was wondering how `babel-register` was working before because it's at the top of the main file, but babel is only registers for subsequent requires. Basically: it doesn't compile the current file it's in, and it looks like some destructuring was added there.

For now, I'll remove that destructuring. What I've done in other apps is have a `run.js` file that does the babel-register and requires the main file, but that feels like a hack. I'll see what Jason thinks when he gets back. I'd rather not have another top-level file.

**Comment by amitzur** [comment]
Got it. I didn't know about babel-register. Thanks.
At least this got me to 6.2.2 finally :)

**Comment by jlongster** [comment]
This is actually the reason cypress was failing on CI because CircleCI uses node 5. Sorry for breaking this!

**Comment by jasonLaster** [comment]
Thanks @amitzur. 

Nice catch.
