### ISSUE TITLE
Move configs to the server

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#286]
Yesterday you mentioned that the server should read the config values and pass them down to the client as a set of feature flags. This lines up with what I was planning on doing, so i thought i'd quickly sketch it out.

https://gist.github.com/jasonLaster/be137dd316bcabf0de55acd55c1bdaec

The benefit is that the client can be dumb and just read the feature flags. We should try to line this up with Prefs. 

Also, the reason that I moved the queryParam parsing and node env check to feature.js was so that we built our set of feature flags in one place, that could be replaced with something like nconf or another config tool that is better at reading configs from files, env vars, and what not...

Anyways, this just some rough thoughts i wanted to share while we were on the topic.

**Comment by jlongster** [comment]
@jasonLaster Looks **great**! That's exactly what I was thinking, but I didn't feel like going through all that quite yet. Once we do that, we can use `fs` methods in the config and be smarter about checking if config files exist.

The query params are not config flags to me. They are just runtime options, and all 3 codepaths can be used in the same session. That's why I'd prefer to keep that code close to where it's actually used, as it makes it clearer how things get set up.

But the DEVTOOLS_PANEL flag probably should be abstracted out.

**Comment by jasonLaster** [comment]
The configs are now managed server side and injected with webpack. This will make it easy to use nconf or another solution.
