### ISSUE TITLE
firefox sourceMapUrls are not available

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#390]
problem some sources have an internal sourcemap, which is not available

Steps to reproduce:
1. open firefox nightly
2. go to localhost:8000/todomvc

```js
{
  id: "server1.conn10.child1/37", 
  url: "http://localhost:8000/todomvc/bower_components/backbone.localStorage/backbone.localStorage.js", 
  isPrettyPrinted: false, 
  sourceMapURL: "internal://sourcemap1/"
}
```

**Comment by jlongster** [comment]
The debugger server uses that URL for sourcemaps it generates, which only happens when pretty-printing. If we never use pretty-printing on the server, you shouldn't ever see that. You may have auto-pretty-print minified sources on, so it's automatically pretty-printing them. For now, we could just make sure that pref is off.

**Comment by jasonLaster** [comment]
oh yeah - that's absolutely true. Just saw the url 

`http://localhost:8000/todomvc/bower_components/backbone.localStorage/backbone.localStorage`
